# In order to install this hook run `pre-commit install`
default_install_hook_types:
  - pre-commit
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version
    rev: "d153933366256874470b9d8395de436c50714f41" # v0.12.9
    hooks:
      - id: uv-lock

  - repo: local 
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
      
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        pass_filenames: false
