apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"bioparser-api:latest","namespace":"toska-playground"},"fieldPath":"spec.template.spec.containers[?(@.name==\"demoapp\")].image","pause":"false"}]
  name: bioparser-api-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bioparser-api
  template:
    metadata:
      labels:
        app: bioparser-api
    spec:
      containers:
        - name: bioparser-api
          image: bioparser-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080