name: Build and Push Local Docker Images

on:
  push:
    branches: [main]

permissions:
  contents: read # fetch code
  packages: write # write image

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    # checkout code
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # GHCR login
      - name: Log in to GHCR
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # build the locally defined Docker images and push them to GHCR
      # API
      - name: Build and push API image
        # assuming the docker file is in the root with name "Dockerfile"
        run: |
          docker build -t ghcr.io/bioparser/bioparser-api:latest .
          docker push ghcr.io/bioparser/bioparser-api:latest
